# permissions for end users to view daemonsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daemonset-viewer-role
rules:
- apiGroups:
  - apps.my.domain
  resources:
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps.my.domain
  resources:
  - daemonsets/status
  verbs:
  - get
