# permissions for end users to edit daemonsets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: daemonset-editor-role
rules:
- apiGroups:
  - apps.my.domain
  resources:
  - daemonsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.my.domain
  resources:
  - daemonsets/status
  verbs:
  - get
